init:
	mvn archetype:generate -DgroupId=com.dmitrydrobysh.app -DartifactId=oop1 -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false

hard_remove:
	rm -rf oop1
